import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    { type: "autogenerated", dirName: "." },
    {
      type: "link",
      label: "Privacy Mining v2 – TL;DR",
      href: "https://hackmd.io/@lionfeeder/HkNOuv9Ege",
    },

    {
      type: "link",
      label: "Whitepaper",
      href: "https://eprint.iacr.org/2023/1082.pdf",
    },
  ],
};

export default sidebars;
